### ISSUE TITLE
Is it possible to disable the section labels?

### ISSUE THREAD

**Issue by andrewtgray** [docbook/xslTNG#208]
Hopefully this is the right place for this sort of thing. 

Is there a way to turn off the section labels? I've tried any parameters that seemed related but I have not been able to turn them off. 
`section-label=false` makes the section labels start at the character f (or whatever the first character is for the parameter value).

**Comment by ndw** [comment]
That sure sounds like a bug. I'll investigate this weekend.

**Comment by ndw** [comment]
I'm confused about `section-label`. AFAICT, that's not an xslTNG parameter. Although your description of what happens when you set it suggests that *something* happens. What version of the stylesheets are you using?

## xslTNG 1.x

For the xslTNG 1.x releases, you can make the section labels go away by changing the title properties:

```xml
<xsl:variable name="v:user-title-properties" as="element()*">
  <title xpath="self::db:section"
         label="false"/>
</xsl:variable>
```

Or, if for example, you only wanted them to go away in chapters, you could use

```xml
<xsl:variable name="v:user-title-properties" as="element()*">
  <title xpath="self::db:section[parent::db:chapter]"
         label="false"/>
</xsl:variable>
```

## xslTNG 2.x

For the xslTNG 2.x releases, you can make the section labels go away by changing the localization:

```xml
<xsl:variable name="v:custom-localizations">
  <locale xmlns="http://docbook.org/ns/docbook/l10n/source"
          language="en"
          english-language-name="English">
    <group name="list-of-titles">
      <template name="section">%c</template>
    </group>
    <group name="title-numbered">
      <template name="section">%c</template>
    </group>
  </locale>
</xsl:variable>
```

Or, again, if you only wanted them to be missing in chapters, you could use:

```xml
<xsl:variable name="v:custom-localizations">
  <locale xmlns="http://docbook.org/ns/docbook/l10n/source"
          language="en"
          english-language-name="English">
    <group name="list-of-titles">
      <template name="chapter/section">%c</template>
    </group>
    <group name="title-numbered">
      <template name="chapter/section">%c</template>
    </group>
  </locale>
</xsl:variable>
```

Note in this case that the name is not an XPath expression.

It's probably a bug that you have to set it in two places. And maybe it's a bug that the name isn't as poweful an expression.

The 2.x series is still in pre-release, so it's subject to change.

**Comment by ndw** [comment]
I'm going to close this, but feel free to reopen it if you haven trouble with those instructions.
