### ISSUE TITLE
Support for landscape pages in PDF

### ISSUE THREAD

**Issue by fsteimke** [docbook/xslTNG#476]
I have a  document with a CALS table with `@orient='land'`. A `div` element with `class='landscape'` is produced, but without effect in the PDF that i get when HTML is processed with Antenna House. Support for landscape pages would include:

To add a `@page` rule for landscape in _docbook-paged.css_. This is already implemented  in the CSS for the _xslTNG Guide_.
```
@page landscape {
  size: landscape;
}

.landscape {
  page: landscape;
}
```

A processing instruction for elements that can be part of a _flow with landscape orientation_. The PI could be `<?db orient='Iandscape' ?>`  or `<?landscape ?>`. I would suggest the following elements:

- book (the whole document in landscape);
- article (either the whole document, or individual articles in a book);
- chapter, section, appendix;
- table and informaltable (HTML as well as CALS, although CALS offers the `@orient` attribute as alternative, because I would prefer a uniform solution for all elements);
- figure and informalfigure

For migration from XSLT 1.0 Stylesheets, a legacy PI `<? landscapeFigure ?>`  as in [Landscape images from the Definitive Guide](http://www.sagehill.net/docbookxsl/LandscapeImage.html) should also be supported for `figure` and `informalfigure`.

Documentation for this feature in the Reference Guide.

Greetings, Frank

**Comment by fsteimke** [comment]
Because the `@role` attribute is too valuable for that. It should be available for semantic assignments, especially for block elements such as section and chapter. The page format, on the other hand, is merely a layout specification. 

Of course, we could use the role attribute with multiple values, like the HTML `@class`, e. g. `section role='uml:class landscape'`, but i would prefer the PI as simpler. And after all, this is what _Processing Instructions_ are made for: its an _Instruction_ how to _process_ this element in an PDF workflow.

**Comment by ndw** [comment]
Processing instructions have their own drawbacks though. It isn't possible to control their placement or content with the schema, so they can go anywhere. (That's generally a feature of processing instructions, but a bug in this sort of situation.) In addition, the semantics are harder to pin down. If

```
<article>
  <?landscape?>
  <title>...</title>
  <para>p1</para>
  <para>p2</para>
</article>
```

makes the article landscape, what does this do?

```
<article>
  <title>...</title>
  <?landscape?>
  <para>p1</para>
  <?portrait?>
  <para>p2</para>
</article>
```

It's probably an attempt to make the "p1" paragraph landscape. Maybe that could be supported, but the author could equally write:

```
<?landscape?>
<article>
  <title>...</title>
  <para>p1</para>
  <?portrait?>
  <para>p2</para>
</article>
```

Which is borderline incoherent.

I see your point about taking user choice away by assigning values to the `role` attribute. Perhaps extension attributes would be better? OTOH, I'm tempted to suggest that the author should be identifying *what* the content is, and that should be driving the presentation choices. So I'm back to thinking it's a role value for the author.

Except, of course, that in real-world publishing, sometimes you just need to say "rotate this because it doesn't fit".

**Comment by fsteimke** [comment]
Well, I understand why you prefer attributes to PIs. It would be good if we could use a common attribute `orient` as in CALS tables. But how would that be possible? We need to stay compliant with the DocBook standard.

- We can't use any of the efficiency attributes, they are made for conditional / profiled text.
- with the exception of the `role` attribute, i can't see any of the common attributes that we could use for page orientation.
- we could use a new attribute from a different namespace in the `info` for block elements, but this is no solution for elements without `info` like `informalfigure` or HTML `informaltable`.
- what do you mean by _extension attributes?_  Sounds interesting.

If there is no other way and we have to use the `@role` attribute, than we should allow multiple values similar to the HTML `class` attribute.

By the way, my use case is the _"rotate because it doesn' t fit"_ case. We have lots of documents with class or sequence diagrams that are best presented in landscape orientation.

I will be on vacation for the next two weeks. I assume that I will rarely be at the computer.

Greetings, Frank

**Comment by ndw** [comment]
You can put attributes from a different namespace on any element, so that's all I meant: `xsltng:orient="landscape"` or something like that. I think the stylesheets already assume that the `role` attribute can be multi-valued, like HTML's `class`, so that still feels like the simplest solution.

Enjoy your vacation!
