### ISSUE TITLE
Include creation of catalog.xml in makeXSLT task?

### ISSUE THREAD

**Issue by hutchkintoot** [docbook/xslTNG#571]
Hi

It would be great if `build/xslt/catalog.xml` was included in the output of `makeXslt` task. Alternatively is there a way to execute the `dist` task without running the xspec tests?

**Comment by ndw** [comment]
I'll take a look. I can't immediately think of any reason why it couldn't be, but it's possible there are more tasks involved.

**Comment by ndw** [comment]
I took a quick look. It isn't going to be absolutely trivial because the dependencies of a broader set of tasks will need to be reviewed. I still don't see any reason why it shouldn't be possible, it just wasn't originally conceived of that way. 

As an immediate workaround, the task `zipStageCatalog` produces the catalog in `build/stage/zip/xslt` without running the tests. You can probably just run the stylesheets from that directory instead of `build/xslt`, if that's what you need.

Out of curiousity, what problem are you solving with the catalog in a local build?

**Comment by hutchkintoot** [comment]
We just wanted a quick way to build a complete `xslt/` folder from source to quickly try out fixes that you have made in this repository but that hasn't been released yet. Right now I'm using the `dist` task. But it takes roughly 10 minutes to complete.

**Comment by ndw** [comment]
Right. I think `zipStageCatalog` and then run from `build/stage/zip/xslt` will work as well and be much quicker!

**Comment by hutchkintoot** [comment]
@ndw Thanks, that worked well. Closing the issue.
