### ISSUE TITLE
Custom attributes not working for title and subtitle elements

### ISSUE THREAD

**Issue by tigloo** [docbook/xslTNG#93]
I'm trying to add id attributes to various elements. This works with db:listitem and db:para, but not with db:title and db:subtitle.

Here's an excerpt from my stylesheet:

```
    <xsl:template match="db:listitem" mode="m:attributes">
        <xsl:attribute name="id"><xsl:value-of select="f:generate-id(.)"/></xsl:attribute>
    </xsl:template>
    <xsl:template match="db:para" mode="m:attributes">
        <xsl:attribute name="id"><xsl:value-of select="f:generate-id(.)"/></xsl:attribute>
    </xsl:template>
    <xsl:template match="db:title" mode="m:attributes">
        <xsl:attribute name="id"><xsl:value-of select="f:generate-id(.)"/></xsl:attribute>
    </xsl:template>
    <xsl:template match="db:subtitle" mode="m:attributes">
        <xsl:attribute name="id"><xsl:value-of select="f:generate-id(.)"/></xsl:attribute>
    </xsl:template>
```

I tried adding m:attributes to db:title and db:subtitle in `templates.xml` but that broke tons of tests. Happy to create a pull request if you can point me in the right direction.

**Comment by ndw** [comment]
This one is a little bit more tricksy, but it's also possible with a customization layer. Generating title pages is really hard because there's so much variation in how users and publishers need them to appear. The [templates mechanism](https://xsltng.docbook.org/guide/ch04.html#header-templates) is an attempt to make this tractable.

For `title` and `subtitle` elements, we make the observation that they're output in the `m:titlepage` mode. For titles, that actually winds up being a call to `m:headline` for the parent element and copying all of that into a customization layer would be kind of ugly.

However, it happens to be the case that when `title` and `subtitle` are processed in `m:titlepage` mode, we will have just created the HTML "h{n}" element for the content. So we can simply begin by outputting the ID attribute.

It's a little bit subtle, but it's probably better than trying to add more parameters for this case (or always outputting ID attributes on the titles because *usually* you want to point to the parent container not the actual title element).

```xml
<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:db="http://docbook.org/ns/docbook"
                xmlns:f="http://docbook.org/ns/docbook/functions"
                xmlns:m="http://docbook.org/ns/docbook/modes"
                xmlns:xs="http://www.w3.org/2001/XMLSchema"
                xmlns="http://www.w3.org/1999/xhtml"
                exclude-result-prefixes="db f m xs"
                version="3.0">

<xsl:import href="../../build/xslt/docbook.xsl"/>

<xsl:template match="db:title|db:subtitle" mode="m:titlepage">
  <xsl:attribute name="id"><xsl:value-of select="f:generate-id(.)"/></xsl:attribute>
  <xsl:next-match/>
</xsl:template>

</xsl:stylesheet>
```

**Comment by tigloo** [comment]
Thanks for the help. I tried your code, but it generates an additional "info1" hierarchy in the ID. For titles, I see IDs like this:

```
R_ch1_info1_title1
R_ch1_info1_subtitle1
```

If I run them through the TOC extractor as discussed in issue #84, the same elements get IDs like this:

```
R_ch1_title1
R_ch1_subtitle1
```

Is there a reason for the additional "info1" part?

I agree on not having to add any more parameters, although for my use case a map that contains the elements which need an ID attribute would be handy - but that's pure cosmetics.

You mention "usually you want to point to the parent container not the actual title element" - anything I should change or improve? I'm splitting up the Docbook document and feed it into Elasticsearch for searching. I reference all elements by ID and use the ID for navigating search results when rendering the full document in the browser. For search results, I'm mainly interested in title, subtitle, listitem and para elements as these provide good structural elements.

That's why the generate-id() function is so handy because I'm relying on it to generate a stable ID.

**Comment by tigloo** [comment]
Ok I think I know what you are trying to point out with your comment. I should be able to achieve the same by processing db:section and db:chapter - in that case the workaround with the titles wouldn't be needed. I'll try that.

**Comment by ndw** [comment]
That's exactly what I meant. I find that using the ID of the container and putting the ID on the surrounding DIV works best. If you get stuck, feel free to reopen this issue or start a new one.
